# Generated by Django 4.2.3 on 2023-07-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparticipants',
            name='user',
            field=models.ManyToManyField(to='user_project.participant'),
        ),
    ]
