# Generated by Django 4.2.3 on 2023-07-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_participants', to='user_project.participant'),
        ),
    ]
