# Generated by Django 4.2.3 on 2023-07-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0002_alter_projectparticipants_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
