# Generated by Django 4.2.3 on 2023-08-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0002_alter_participant_type_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='project',
        ),
        migrations.AddField(
            model_name='participant',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='user_project.projects'),
        ),
    ]
