# Generated by Django 4.2.3 on 2023-08-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0003_alter_participant_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparticipants',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='project_participants', to='user_project.projects'),
            preserve_default=False,
        ),
    ]
