# Generated by Django 4.2.3 on 2023-07-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0003_participant_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparticipants',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='user_project.participant'),
        ),
    ]
