# Generated by Django 4.2.3 on 2023-07-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0003_remove_command_user_command_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='user_project.participant'),
        ),
    ]
