# Generated by Django 4.2.3 on 2023-07-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0004_alter_projectparticipants_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=70),
        ),
    ]
