# Generated by Django 4.2.3 on 2023-08-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0004_alter_participant_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='stack',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
