# Generated by Django 4.2.3 on 2023-08-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0004_alter_projectparticipants_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='user_project.projects'),
        ),
    ]
