# Generated by Django 4.2.3 on 2023-08-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0005_alter_participant_city_alter_participant_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='project',
            field=models.ManyToManyField(blank=True, to='user_project.projects'),
        ),
    ]
