# Generated by Django 4.2.3 on 2023-09-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0006_remove_templatelatter_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='project',
            field=models.ManyToManyField(to='user_project.projects'),
        ),
    ]
