# Generated by Django 4.2.2 on 2023-06-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='participants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_project.participant'),
        ),
    ]
