# Generated by Django 4.2.2 on 2023-06-30 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0002_projects_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='participants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='user_project.participant'),
        ),
    ]
