# Generated by Django 4.2.3 on 2023-08-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0002_alter_projects_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparticipants',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_lead', to='user_project.participant'),
        ),
    ]
