# Generated by Django 4.2.3 on 2023-08-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0003_alter_projectparticipants_team_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
