# Generated by Django 4.2.3 on 2023-08-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0004_alter_participant_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectparticipants',
            name='team_lead',
        ),
        migrations.AddField(
            model_name='projectparticipants',
            name='team_lead',
            field=models.ManyToManyField(blank=True, null=True, related_name='team_lead', to='user_project.participant'),
        ),
    ]
