# Generated by Django 4.2.2 on 2023-06-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0004_alter_projects_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='participants',
        ),
        migrations.AddField(
            model_name='projects',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_participants', to='user_project.participant'),
        ),
    ]
