# Generated by Django 4.2.3 on 2023-08-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_project', '0005_remove_projectparticipants_team_lead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatelatter',
            name='pdf_file',
        ),
    ]
