# Generated by Django 4.2.3 on 2023-07-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_authtoken_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
