# Generated by Django 4.2.3 on 2023-07-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('users', '0004_delete_authtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('life_time_token', models.DateTimeField()),
            ],
            bases=('authtoken.token',),
        ),
    ]
