# Generated by Django 4.2.3 on 2023-07-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='life_time_token',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
