import { getExpValue, getProjValue, getTypeValue } from './getValues';
import {
	cityPlaceholder,
	emailPlaceholder,
	experiencePlaceholder,
	lastnamePlaceholder,
	linkedInPlaceholder,
	namePlaceholder,
	phoneNumberFormat,
	projectPlaceholder,
	stackPlaceholder,
	typePlaceholder,
} from './placeholders';
import {
	cityRegex,
	discordRegex,
	emailRegex,
	lastNameRegex,
	linkedRegex,
	nameRegex,
	phoneNumberRegex,
	stackRegex,
} from './regex';
import { requiredField } from './requiredField';
export {
	lastNameRegex,
	stackRegex,
	phoneNumberRegex,
	phoneNumberFormat,
	emailRegex,
	discordRegex,
	linkedRegex,
	getExpValue,
	getProjValue,
	getTypeValue,
	requiredField,
	nameRegex,
	emailPlaceholder,
	linkedInPlaceholder,
	cityRegex,
	experiencePlaceholder,
	namePlaceholder,
	lastnamePlaceholder,
	stackPlaceholder,
	typePlaceholder,
	projectPlaceholder,
	cityPlaceholder,
};
